"""
Zero-shot evaluation on the held-out test sets from the progressive finetuning splits.

This script evaluates model/fold checkpoints found under:
    results/experiments/complete_experiment/ablations/<model_key>/fold_XX/checkpoints/best_f1.pt

Run:
    python scripts/04_zero_shot_cross_volcano.py

On the repeated 80/20 target-volcano splits generated by script 01b:
    data/prepared_data/progressive_finetuning/<VOLCANO>/fold_XX/test_80.npz

Outputs are written to:
    results/experiments/complete_experiment/zero_shot_cross_volcano/
"""

from __future__ import annotations

import argparse
import gc
import json
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import torch

import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utils.core.io import (
    append_row_csv,
    checkpoint_path_for_fold,
    load_completed_keys,
    load_training_fold_summary,
)
from utils.core.registry import MODEL_SPECS
from utils.evaluation.eval_runtime import (
    evaluate_event_detection_checkpoint,
    evaluate_multistation_checkpoint as evaluate_multistation_checkpoint_on_target,
    load_checkpoint_into_model,
)
from utils.evaluation.metrics_core import (
    event_f1_agnostic_from_confusion_matrix,
    macro_f1_6c_from_confusion_matrix,
    summarize_scalar_values,
)
from utils.core.paths import (
    parse_csv_selection,
    resolve_project_path,
)
from utils.training.train_utils import (
    cleanup_gpu_cache,
    save_confusion_matrix_image,
)

CLASS_NAMES = ["VT", "LP", "TR", "AV", "IC"]
FOLDS = range(1, 6)

RESULTS_ROOT = PROJECT_ROOT / "results"
EXPERIMENTS_ROOT = RESULTS_ROOT / "experiments"
DEFAULT_EXPERIMENT_ROOT = EXPERIMENTS_ROOT / "complete_experiment"
DEFAULT_CROSS_DATA_ROOT = (
    PROJECT_ROOT / "data" / "prepared_data" / "progressive_finetuning"
)
DEFAULT_OUTPUT_NAME = "zero_shot_cross_volcano"
DEFAULT_POINTER_NAME = "pointer_zero_shot_cross_volcano.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate zero-shot performance on progressive finetuning test sets "
            "for all model/fold checkpoints in complete_experiment/ablations."
        )
    )
    parser.add_argument(
        "--experiment-root",
        type=Path,
        default=DEFAULT_EXPERIMENT_ROOT,
        help="Root folder containing 'ablations' (default: complete_experiment).",
    )
    parser.add_argument(
        "--cross-data-root",
        type=Path,
        default=DEFAULT_CROSS_DATA_ROOT,
        help=(
            "Progressive finetuning dataset root containing "
            "<VOLCANO>/fold_XX/test_80.npz."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Output directory for zero-shot reports. Defaults to "
            "<experiment-root>/zero_shot_cross_volcano."
        ),
    )
    parser.add_argument(
        "--models",
        type=str,
        default=None,
        help="Comma-separated model keys to evaluate. Default: discovered model folders.",
    )
    parser.add_argument(
        "--targets",
        type=str,
        default=None,
        help="Comma-separated target volcano names. Default: all hold-out targets.",
    )
    parser.add_argument(
        "--allow-missing-models",
        action="store_true",
        help="Skip missing model folders instead of failing.",
    )
    parser.add_argument(
        "--allow-missing-folds",
        action="store_true",
        help="Skip missing fold checkpoints instead of failing.",
    )
    parser.add_argument(
        "--station-scramble-seed",
        type=int,
        default=42,
        help="Base seed used to build deterministic per-sample station permutations.",
    )
    return parser.parse_args()


def discover_loo_target_test_paths(
    cross_data_root: Path,
) -> dict[str, list[tuple[int, Path]]]:
    """Map target volcano name -> sorted repeat_id/test_80.npz pairs."""
    if not cross_data_root.exists():
        raise FileNotFoundError(
            f"Progressive finetuning root not found: {cross_data_root}"
        )

    target_to_test_npz: dict[str, list[tuple[int, Path]]] = {}
    for volcano_dir in sorted(cross_data_root.iterdir()):
        if not volcano_dir.is_dir():
            continue

        target = volcano_dir.name.strip()
        if len(target) == 0:
            continue

        repeat_entries: list[tuple[int, Path]] = []
        for fold_dir in sorted(volcano_dir.glob("fold_*")):
            if not fold_dir.is_dir():
                continue

            test_npz_path = fold_dir / "test_80.npz"
            if not test_npz_path.exists():
                continue

            try:
                repeat_id = int(fold_dir.name.split("_")[-1])
            except ValueError as exc:
                raise RuntimeError(
                    f"Invalid progressive finetuning fold directory: {fold_dir.name}"
                ) from exc

            repeat_entries.append((repeat_id, test_npz_path))

        if len(repeat_entries) > 0:
            repeat_entries.sort(key=lambda item: item[0])
            target_to_test_npz[target] = repeat_entries

    if len(target_to_test_npz) == 0:
        raise RuntimeError(
            "No held-out test manifests found under progressive finetuning root: "
            f"{cross_data_root}"
        )

    return dict(sorted(target_to_test_npz.items()))


def write_aggregate_reports(out_dir: Path) -> None:
    fold_metrics_path = out_dir / "zero_shot_fold_metrics.csv"
    if not fold_metrics_path.exists():
        raise FileNotFoundError(f"Missing fold metrics file: {fold_metrics_path}")

    fold_df = pd.read_csv(
        fold_metrics_path,
        sep=";",
        decimal=",",
        encoding="utf-8-sig",
    )
    if len(fold_df) == 0:
        raise RuntimeError(f"Fold metrics file is empty: {fold_metrics_path}")

    summary_rows = []
    per_class_f1_rows = []

    def _metric_column(df: pd.DataFrame, canonical: str, legacy: str) -> pd.Series:
        if canonical in df.columns:
            return df[canonical].astype(float)
        if legacy in df.columns:
            return df[legacy].astype(float)
        raise KeyError(
            f"Missing metric columns '{canonical}' and '{legacy}' in fold metrics CSV."
        )

    grouped = fold_df.groupby(["model_key", "target_volcano"], sort=True)
    for (model_key, target), grp in grouped:
        macro_f1_summary = summarize_scalar_values(
            _metric_column(grp, "macro_f1_6c", "test_mean_f1").tolist()
        )
        event_f1_agnostic_summary = summarize_scalar_values(
            _metric_column(grp, "event_f1_agnostic", "test_event_f1_agnostic").tolist()
        )
        event_iou_summary = summarize_scalar_values(
            _metric_column(grp, "event_iou_active_only", "test_mean_iou").tolist()
        )
        loss_summary = summarize_scalar_values(grp["test_loss"].astype(float).tolist())

        display_names = grp["model_display_name"].dropna().unique().tolist()
        display_name = (
            str(display_names[0]) if len(display_names) > 0 else str(model_key)
        )
        summary_row = {
            "model_key": str(model_key),
            "model_display_name": display_name,
            "target_volcano": str(target),
            "n_folds": int(len(grp)),
            "macro_f1_6c_mean": float(macro_f1_summary["mean"]),
            "macro_f1_6c_std": float(macro_f1_summary["std"]),
            "event_f1_agnostic_mean": float(event_f1_agnostic_summary["mean"]),
            "event_f1_agnostic_std": float(event_f1_agnostic_summary["std"]),
            "event_iou_active_only_mean": float(event_iou_summary["mean"]),
            "event_iou_active_only_std": float(event_iou_summary["std"]),
            "test_loss_mean": float(loss_summary["mean"]),
            "test_loss_std": float(loss_summary["std"]),
        }

        per_class_f1_row = {
            "model_key": str(model_key),
            "model_display_name": display_name,
            "target_volcano": str(target),
        }

        for class_name in CLASS_NAMES:
            f1_col = f"test_f1_{class_name}"
            f1_summary = summarize_scalar_values(grp[f1_col].astype(float).tolist())

            summary_row[f"{f1_col}_mean"] = float(f1_summary["mean"])
            summary_row[f"{f1_col}_std"] = float(f1_summary["std"])

            per_class_f1_row[f"{class_name}_mean"] = float(f1_summary["mean"])
            per_class_f1_row[f"{class_name}_std"] = float(f1_summary["std"])

        summary_rows.append(summary_row)
        per_class_f1_rows.append(per_class_f1_row)

    summary_df = pd.DataFrame(summary_rows).sort_values(
        by=["target_volcano", "macro_f1_6c_mean"],
        ascending=[True, False],
    )
    summary_df.to_csv(
        out_dir / "zero_shot_summary_by_model_target.csv",
        index=False,
        encoding="utf-8-sig",
        sep=";",
        decimal=",",
    )

    pd.DataFrame(per_class_f1_rows).sort_values(
        by=["target_volcano", "model_key"],
        ascending=[True, True],
    ).to_csv(
        out_dir / "zero_shot_per_class_f1.csv",
        index=False,
        encoding="utf-8-sig",
        sep=";",
        decimal=",",
    )

    comparisons_dir = out_dir / "comparisons"
    comparisons_dir.mkdir(parents=True, exist_ok=True)

    for target in sorted(summary_df["target_volcano"].unique().tolist()):
        target_df = summary_df[summary_df["target_volcano"] == target].copy()
        target_dir = comparisons_dir / str(target)
        target_dir.mkdir(parents=True, exist_ok=True)

        target_df.sort_values(by="macro_f1_6c_mean", ascending=False).to_csv(
            target_dir / "rank_by_macro_f1_6c.csv",
            index=False,
            encoding="utf-8-sig",
            sep=";",
            decimal=",",
        )
        target_df.sort_values(by="event_iou_active_only_mean", ascending=False).to_csv(
            target_dir / "rank_by_event_iou_active_only.csv",
            index=False,
            encoding="utf-8-sig",
            sep=";",
            decimal=",",
        )
        target_df.sort_values(by="event_f1_agnostic_mean", ascending=False).to_csv(
            target_dir / "rank_by_event_f1_agnostic.csv",
            index=False,
            encoding="utf-8-sig",
            sep=";",
            decimal=",",
        )


def main() -> None:
    args = parse_args()

    experiment_root = resolve_project_path(args.experiment_root, PROJECT_ROOT)
    cross_data_root = resolve_project_path(args.cross_data_root, PROJECT_ROOT)

    out_dir = (
        resolve_project_path(args.output_dir, PROJECT_ROOT)
        if args.output_dir is not None
        else (experiment_root / DEFAULT_OUTPUT_NAME)
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    ablations_root = experiment_root / "ablations"
    if not ablations_root.exists():
        raise FileNotFoundError(f"Ablations root not found: {ablations_root}")
    discovered_model_dirs = sorted(
        [p.name for p in ablations_root.iterdir() if p.is_dir()]
    )

    available_model_keys = [
        model_key for model_key in discovered_model_dirs if model_key in MODEL_SPECS
    ]
    unknown_dirs = sorted(set(discovered_model_dirs) - set(available_model_keys))
    if len(unknown_dirs) > 0:
        print(
            "[WARN] Skipping model folders not present in registry: " f"{unknown_dirs}"
        )

    if args.models is not None:
        selected_models = parse_csv_selection(
            args.models,
            available_model_keys,
            "model keys",
        )
    else:
        selected_models = list(available_model_keys)

    if len(selected_models) == 0:
        raise RuntimeError("No models selected for evaluation.")

    target_to_test_npz = discover_loo_target_test_paths(cross_data_root)
    discovered_targets = list(target_to_test_npz.keys())
    selected_targets = parse_csv_selection(
        args.targets, discovered_targets, "target volcanoes"
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    run_manifest = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "project_root": str(PROJECT_ROOT),
        "experiment_root": str(experiment_root),
        "cross_data_root": str(cross_data_root),
        "output_dir": str(out_dir),
        "device": str(device),
        "batch_size_source": "model_registry",
        "selected_models": selected_models,
        "selected_targets": selected_targets,
        "target_test_npz": {
            target: [
                {"repeat_id": int(repeat_id), "path": str(test_npz_path)}
                for repeat_id, test_npz_path in target_to_test_npz[target]
            ]
            for target in selected_targets
        },
        "allow_missing_models": bool(args.allow_missing_models),
        "allow_missing_folds": bool(args.allow_missing_folds),
        "save_confusion_matrices": True,
        "scramble_stations": False,
        "station_scramble_seed": int(args.station_scramble_seed),
        "folds": [int(f) for f in FOLDS],
        "model_specs": {
            key: {
                "batch_size": int(MODEL_SPECS[key]["batch_size"]),
                "model_kwargs": MODEL_SPECS[key]["model_kwargs"],
                "eval_matching": MODEL_SPECS[key].get("eval_matching", {}),
            }
            for key in selected_models
        },
    }
    with (out_dir / "run_manifest.json").open("w", encoding="utf-8") as f:
        json.dump(run_manifest, f, indent=2)

    print("=" * 80)
    print("Zero-shot progressive finetuning evaluation")
    print(f"Experiment root: {experiment_root}")
    print(f"Cross data root: {cross_data_root}")
    print(f"Output dir: {out_dir}")
    print(f"Models ({len(selected_models)}): {selected_models}")
    print(f"Targets ({len(selected_targets)}): {selected_targets}")
    print(f"Scramble stations: {False}")
    print(f"Device: {device}")
    print("=" * 80)

    fieldnames = [
        "model_key",
        "model_display_name",
        "fold",
        "repeat_id",
        "target_volcano",
        "n_test",
        "checkpoint",
        "train_best_epoch",
        "train_best_val_mean_f1",
        "test_loss",
        "macro_f1_6c",
        "event_f1_agnostic",
        "event_iou_active_only",
        "test_mean_f1",
        "test_event_f1_agnostic",
        "test_mean_iou",
        "n_active_classes",
        "active_classes",
    ]
    for class_name in CLASS_NAMES:
        fieldnames.append(f"test_f1_{class_name}")

    completed_keys = load_completed_keys(
        out_dir / "zero_shot_fold_metrics.csv",
        id_columns=["model_key", "fold", "repeat_id", "target_volcano"],
    )
    if len(completed_keys) > 0:
        print(
            f"Resuming run: found {len(completed_keys)} completed evaluations in fold metrics CSV."
        )

    newly_completed = 0

    for model_key in selected_models:
        if model_key not in MODEL_SPECS:
            print(f"[WARN] Skipping unknown model key not in registry: {model_key}")
            continue

        model_spec = MODEL_SPECS[model_key]
        trainer_kind = str(model_spec["trainer_kind"])
        model_kwargs = dict(model_spec["model_kwargs"])

        print(f"\n[MODEL] {model_key}")
        model_root = ablations_root / model_key
        if not model_root.exists():
            msg = f"Missing model folder: {model_root}"
            if args.allow_missing_models:
                print(f"[WARN] {msg}")
                continue
            raise FileNotFoundError(msg)

        for fold_id in FOLDS:
            ckpt_path = checkpoint_path_for_fold(model_root, fold_id)
            if not ckpt_path.exists():
                msg = f"Missing checkpoint: {ckpt_path}"
                if args.allow_missing_folds:
                    print(f"[WARN] {msg}")
                    continue
                raise FileNotFoundError(msg)

            train_fold_summary = load_training_fold_summary(model_root, fold_id)
            train_best_epoch = (
                int(train_fold_summary["best_epoch"])
                if train_fold_summary is not None and "best_epoch" in train_fold_summary
                else None
            )
            train_best_val_mean_f1 = (
                float(train_fold_summary["best_val_mean_f1"])
                if train_fold_summary is not None
                and "best_val_mean_f1" in train_fold_summary
                else None
            )

            for target_name in selected_targets:
                for repeat_id, test_npz_path in target_to_test_npz[target_name]:
                    eval_key = (model_key, int(fold_id), int(repeat_id), target_name)
                    if eval_key in completed_keys:
                        print(
                            f"  [SKIP] fold={fold_id:02d} target={target_name} repeat={repeat_id:02d} already completed"
                        )
                        continue

                    if not test_npz_path.exists():
                        raise FileNotFoundError(
                            f"Missing test artifact: {test_npz_path}"
                        )

                    batch_size = int(model_spec["batch_size"])

                    if trainer_kind == "segmentation":
                        model_kwargs_runtime = dict(model_kwargs)
                        uses_station_info = bool(
                            model_kwargs_runtime.get("use_distance_attn_bias", False)
                            or model_kwargs_runtime.get(
                                "use_distance_bottleneck_emb", False
                            )
                        )
                        if uses_station_info:
                            model_kwargs_runtime["volcano_name"] = str(target_name)

                        model = model_spec["model_cls"](**model_kwargs_runtime).to(
                            device
                        )
                        if uses_station_info:
                            load_checkpoint_into_model(
                                model=model,
                                checkpoint_path=ckpt_path,
                                device=device,
                                trainer_kind=trainer_kind,
                                allowed_missing_keys=("station_dist",),
                                ignore_checkpoint_keys=("station_dist",),
                            )
                        else:
                            load_checkpoint_into_model(
                                model=model,
                                checkpoint_path=ckpt_path,
                                device=device,
                                trainer_kind=trainer_kind,
                            )

                        (
                            f1_per_class,
                            mean_f1,
                            mean_iou,
                            eval_loss,
                            cm,
                            n_samples,
                            active_event_ids,
                        ) = evaluate_multistation_checkpoint_on_target(
                            model=model,
                            test_npz_path=test_npz_path,
                            batch_size=batch_size,
                            device=device,
                            scramble_stations=False,
                            station_scramble_seed=int(args.station_scramble_seed),
                        )
                    elif trainer_kind == "event_detection":
                        model = model_spec["model_cls"](**model_kwargs).to(device)
                        load_checkpoint_into_model(
                            model=model,
                            checkpoint_path=ckpt_path,
                            device=device,
                            trainer_kind=trainer_kind,
                        )
                        (
                            f1_per_class,
                            mean_f1,
                            mean_iou,
                            eval_loss,
                            cm,
                            n_samples,
                            active_event_ids,
                            _,
                        ) = evaluate_event_detection_checkpoint(
                            model=model,
                            test_npz_path=test_npz_path,
                            batch_size=batch_size,
                            device=device,
                            scramble_stations=False,
                            station_scramble_seed=int(args.station_scramble_seed),
                            model_spec=model_spec,
                        )
                    else:
                        raise ValueError(
                            f"Unsupported trainer kind '{trainer_kind}' for key '{model_key}'"
                        )

                    if int(cm.shape[0]) == 6:
                        macro_f1_6c = float(macro_f1_6c_from_confusion_matrix(cm))
                        event_f1_agnostic = float(
                            event_f1_agnostic_from_confusion_matrix(cm)
                        )
                    else:
                        # Legacy event-only confusion matrices do not include BG.
                        macro_f1_6c = float(mean_f1)
                        event_f1_agnostic = float(mean_f1)

                    row = {
                        "model_key": model_key,
                        "model_display_name": str(model_key),
                        "fold": int(fold_id),
                        "repeat_id": int(repeat_id),
                        "target_volcano": target_name,
                        "n_test": int(n_samples),
                        "checkpoint": str(ckpt_path),
                        "train_best_epoch": train_best_epoch,
                        "train_best_val_mean_f1": train_best_val_mean_f1,
                        "test_loss": float(eval_loss),
                        "macro_f1_6c": float(macro_f1_6c),
                        "event_f1_agnostic": float(event_f1_agnostic),
                        "event_iou_active_only": float(mean_iou),
                        "test_mean_f1": float(mean_f1),
                        "test_event_f1_agnostic": float(event_f1_agnostic),
                        "test_mean_iou": float(mean_iou),
                        "n_active_classes": int(len(active_event_ids)),
                        "active_classes": ",".join(
                            [CLASS_NAMES[x - 1] for x in active_event_ids]
                        ),
                    }

                    for idx, class_name in enumerate(CLASS_NAMES):
                        row[f"test_f1_{class_name}"] = float(f1_per_class[idx])

                    append_row_csv(
                        out_dir / "zero_shot_fold_metrics.csv",
                        row=row,
                        fieldnames=fieldnames,
                    )
                    append_row_csv(
                        out_dir / "by_target" / target_name / "fold_metrics.csv",
                        row=row,
                        fieldnames=fieldnames,
                    )
                    append_row_csv(
                        out_dir / "by_fold" / model_key / f"fold_{fold_id:02d}.csv",
                        row=row,
                        fieldnames=fieldnames,
                    )
                    completed_keys.add(eval_key)
                    newly_completed += 1

                    cm_dir = (
                        out_dir
                        / "confusion_matrices"
                        / model_key
                        / f"fold_{fold_id:02d}"
                    )
                    cm_dir.mkdir(parents=True, exist_ok=True)
                    cm_path = (
                        cm_dir
                        / f"cm_{target_name}_repeat_{repeat_id:02d}_test80_best_f1.png"
                    )
                    save_confusion_matrix_image(
                        cm=cm,
                        labels=CLASS_NAMES,
                        out_path=cm_path,
                        title=(
                            f"Zero-shot CM | {model_key} | fold {fold_id:02d} | "
                            f"target {target_name} | repeat {repeat_id:02d}"
                        ),
                    )

                    print(
                        f"  fold={fold_id:02d} target={target_name} repeat={repeat_id:02d} "
                        f"macro_f1_6c={float(row['macro_f1_6c']):.4f} "
                        f"event_f1_agnostic={float(row['event_f1_agnostic']):.4f} "
                        f"event_iou_active_only={float(row['event_iou_active_only']):.4f}"
                    )

                    del cm
                    del model
                    cleanup_gpu_cache()

                    gc.collect()
        gc.collect()

    if newly_completed == 0 and len(completed_keys) == 0:
        raise RuntimeError("No evaluations were executed. Check models/folds/targets.")

    write_aggregate_reports(out_dir=out_dir)

    latest_dir = RESULTS_ROOT / "latest"
    latest_dir.mkdir(parents=True, exist_ok=True)
    with (latest_dir / DEFAULT_POINTER_NAME).open("w", encoding="utf-8") as f:
        json.dump(
            {
                "output_dir": str(out_dir),
                "updated_at": datetime.now().isoformat(timespec="seconds"),
            },
            f,
            indent=2,
        )

    print("=" * 80)
    print("Zero-shot evaluation complete")
    print(f"Fold metrics: {out_dir / 'zero_shot_fold_metrics.csv'}")
    print(f"Summary: {out_dir / 'zero_shot_summary_by_model_target.csv'}")
    print(f"Comparisons: {out_dir / 'comparisons'}")
    print("=" * 80)


if __name__ == "__main__":
    main()
